awesome-stickers/config/routes.rb
Rails.application.routes.draw do

  resources :stickers

  root 'home#index'

  resources :products

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end

end

awesome-stickers/app/models/product.rb
class Product < ActiveRecord::Base
end

awesome-stickers/app/models/sticker.rb
class Sticker < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  # before_save PhotoUploader::extension_white_list

  # use carrierwave to upload photos of the sticker
  mount_uploader :photo, PhotoUploader
end

awesome-stickers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

awesome-stickers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :'home/index'
  end
end

awesome-stickers/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products_frontpage = @products.limit(6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:photo, :name, :description, :size, :buy_price, :sell_price)
    end
end

awesome-stickers/app/controllers/stickers_controller.rb
class StickersController < ApplicationController
  before_action :set_sticker, only: [:show, :edit, :update, :destroy]

  # GET /stickers
  # GET /stickers.json
  def index
    @stickers = Sticker.all
  end

  # GET /stickers/1
  # GET /stickers/1.json
  def show
  end

  # GET /stickers/new
  def new
    @sticker = Sticker.new
  end

  # GET /stickers/1/edit
  def edit
  end

  # POST /stickers
  # POST /stickers.json
  def create
    @sticker = Sticker.new(sticker_params)

    respond_to do |format|
      if @sticker.save
        format.html { redirect_to @sticker, notice: 'Sticker was successfully created.' }
        format.json { render :show, status: :created, location: @sticker }
      else
        format.html { render :new }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stickers/1
  # PATCH/PUT /stickers/1.json
  def update
    respond_to do |format|
      if @sticker.update(sticker_params)
        format.html { redirect_to @sticker, notice: 'Sticker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sticker }
      else
        format.html { render :edit }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickers/1
  # DELETE /stickers/1.json
  def destroy
    @sticker.destroy
    respond_to do |format|
      format.html { redirect_to stickers_url, notice: 'Sticker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticker
      @sticker = Sticker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticker_params
      params.require(:sticker).permit(:photo, :name, :description, :tags)
    end
end

awesome-stickers/app/helpers/application_helper.rb
module ApplicationHelper
end

awesome-stickers/app/helpers/home_helper.rb
module HomeHelper
end

awesome-stickers/app/helpers/products_helper.rb
module ProductsHelper
end

awesome-stickers/app/helpers/stickers_helper.rb
module StickersHelper
end

awesome-stickers/app/views/home/index.html.erb
<ul class="example-orbit" data-orbit>
  <li>
    <%= image_tag "awesome-stickers-slider1.jpg" %>
    <div class="orbit-caption">
      Unlimited designs...awesome quality!
    </div>
  </li>
  <li class="active">
    <%= image_tag "awesome-stickers-slider2.jpg" %>
    <div class="orbit-caption">
      Bumper & car stickers.
    </div>
  </li>
  <li>
    <%= image_tag "awesome-stickers-slider3.jpg" %>
    <div class="orbit-caption">
      Mobile phone & laptop stickers.
    </div>
  </li>
</ul>

<!-- start thumbnail section after the slider -->
<section class="row">
  <h4>Get started, select the sticker you'd like:</h4>
  <%= link_to image_tag("awesome-stickers-thumbnails1.jpg"), stickers_path, class: "th" %>
  <%= link_to image_tag("awesome-stickers-thumbnails2.jpg"), stickers_path, class: "th" %>
  <%= link_to image_tag("awesome-stickers-thumbnails3.jpg"), stickers_path, class: "th" %>
  <%= link_to image_tag("awesome-stickers-thumbnails4.jpg"), stickers_path, class: "th" %>
  <hr>
</section>
<!-- end thumbnail section after the slider -->
<section class="row">
  <h4>How it works:</h4>
  <p>This is basically how it works: You select the sticker you'd like e.g. "Car Stickers", select the design you'd
    like, then contact us to get the nearest stockist. At the same time, you can still order online and get the sticker
    delivered to you for free. <span class="[success alert secondary] label">That's what we call awesome!</span></p>
</section>

awesome-stickers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:name) ? yield(:name) : "Awesome Stickers" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
     <div class="row">
      <div class="large-12 columns">
      <!-- Navigation -->

      <div class="row">
        <div class="large-12 columns">
          <nav class="top-bar" data-topbar>
            <ul class="title-area"><!-- Title Area -->

              <li class="name">
                <h1><%= link_to image_tag("awesome-stickers-web-app-logo.png"), root_path %></h1>
              </li>

              <li class="toggle-topbar menu-icon">
                <a href="#"><span>menu</span></a>
              </li>
            </ul>

          </nav><!-- End Top Bar -->
        </div>
      </div>
        <!-- End Navigation -->
        <%= yield %>
        <!-- End Thumbnails -->

        </div>
      </div><!-- Footer -->

      <footer class="row">
        <div class="large-12 columns">
          <hr>
          <div class="row">
            <div class="large-6 columns">
              <p>&copy; 2014. <span class="label">AwesomeStickers.net</span> Powered by: <%= link_to "The Useful Internet", "http://www.theusefulinternet.com" %></p>

            </div>

            <div class="large-6 columns">
              <ul class="inline-list right">
                <li>
                  <%= link_to "Credits", credits_page_path %>
                </li>

                <li>
                  <%= link_to "Help", help_page_path %>
                </li>

                <li>
                  <%= link_to "About", about_page_path %>
                </li>

                <li>
                  <%= link_to "Privacy", privacy_page_path %>
                </li>

                <li>
                  <%= link_to "Talk to us", contact_page_path %>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </footer>
      <%= javascript_include_tag "application" %>
  </body>
</html>

awesome-stickers/app/views/pages/contact.html.erb
<h3>Talk to us:</h3>
<hr>
<p>Use the form below to get in touch with us.</p>

awesome-stickers/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :buy_price %><br>
    <%= f.number_field :buy_price %>
  </div>
  <div class="field">
    <%= f.label :sell_price %><br>
    <%= f.number_field :sell_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

awesome-stickers/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

awesome-stickers/app/views/products/index.html.erb
<% @products_frontpage.each do |product| %>
<ul class="small-block-grid-3">
      <li><%= image_tag "man-city.jpg" %></li>
      <li><%= product.photo %></li>
      <li><%= product.name %></li>
      <li><%= product.sell_price %></li>
      <li><%= link_to 'Show', product %></li>
      <li><%= link_to 'Edit', edit_product_path(product) %></li>
      <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>
<% end %>

awesome-stickers/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

awesome-stickers/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @product.photo %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Buy price:</strong>
  <%= @product.buy_price %>
</p>

<p>
  <strong>Sell price:</strong>
  <%= @product.sell_price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

awesome-stickers/app/views/stickers/_form.html.erb
<%= form_for(@sticker) do |f| %>
  <% if @sticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sticker.errors.count, "error") %> prohibited this sticker from being saved:</h2>

      <ul>
      <% @sticker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %><br>
    <%= image_tag(@sticker.photo_url) if @sticker.photo? %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

awesome-stickers/app/views/stickers/edit.html.erb
<h1>Editing sticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticker %> |
<%= link_to 'Back', stickers_path %>

awesome-stickers/app/views/stickers/index.html.erb
<h4>All stickers</h4>

<section class="row">
  <h4>5cmX5cm stickers</h4>
  <% @stickers.each do |sticker| %>
    <div class="th"><%= image_tag(sticker.photo)  %></div>
    <span class="label"><%= sticker.name %></span>
  <% end %>
  <hr>
</section>

<br>

<%= link_to 'New Sticker', new_sticker_path %>

awesome-stickers/app/views/stickers/new.html.erb
<h1>New sticker</h1>

<%= render 'form' %>

<%= link_to 'Back', stickers_path %>

awesome-stickers/app/views/stickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @sticker.photo %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sticker.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sticker.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @sticker.tags %>
</p>

<%= link_to 'Edit', edit_sticker_path(@sticker) %> |
<%= link_to 'Back', stickers_path %>